BUGFIX: Remove double slashes in //refund.
ili/Yandex.Checkout.V3 pull request #2
Opened 2018-10-23 07:29 UTC by bzaar

И всякие переименования

2018-10-24 14:51 UTC, ili requested changes

2018-10-24 14:51 UTC, ili commented on Yandex.Checkout.V3/Client.cs
> +        private readonly HttpClient _httpClient = new HttpClient();
Не так лучше не делать. В [документации](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=netframework-4.7.2#remarks) в конце ремарок приведён как раз пример со статикой.

В оффисе я под нагрузкой тестировал оба варианта, и статир ридонли дает больший перфоманс и никаких коллизий (в принципе, оно и понятно, ввиду того что они используют отдельные пулы соединений, судя по док-ии)

2018-10-24 14:52 UTC, ili commented
Ну и конфликты порешать надо :)

2018-10-30 18:44 UTC, bzaar commented on Yandex.Checkout.V3/Client.cs
> +        private readonly HttpClient _httpClient = new HttpClient();
Если оставить static, то будут следующие проблемы:
 1. У пользователя нашего Client не будет возможности вызвать HttpClient.Dispose, чтобы освободить системные ресурсы (CancellationTokens, unmanaged streams). Здравствуйте, утечки памяти. Скорее всего, небольшие, но все же. К тому же рекомендация делать HttpClient static приводит к проблемам с blue-green deployment ([статья](http://byterot.blogspot.com/2016/07/singleton-httpclient-dns.html)).
 2. HttpClient не совсем потокобезопасный, как отмечает та же документация. Как только кто-то решит воспользоваться, например, свойствами Timeout или DefaultRequestHeaders, так тут же внесет в код трудноуловимую проблему, которая будет выстреливать раз в пятилетку и крешить весь сервер.
 3. На корню зарубается возможность unit-тестирования класса Client.

Предлагаю сделать так:  Client будет управлять временем жизни экземпляра HttpClient: в конструкторе создавать, а в Dispose вызывать HttpClient.Dispose. Тогда все правила о времени жизни HttpClient будет справедливы для Client: хочешь - делай его static, хочешь - делай Dispose, когда он тебе не нужен.

2018-10-31 09:02 UTC, ili commented on Yandex.Checkout.V3/Client.cs
> +        private readonly HttpClient _httpClient = new HttpClient();
Тогда нужен конструктор, принимающий HttpClient, в этом случае Client ничего с переданным экземпляром делать не должен

2018-10-31 12:16 UTC, bzaar commented on Yandex.Checkout.V3/Client.cs
> +        private readonly HttpClient _httpClient = new HttpClient();
Неплохое решение, то не совсем гуманно заставлять пользователей класса Client каждый раз создавать еще и HttpClient. К тому же, они могут решить, что раз HttpClient общий, то можно его передать еще куда-нибудь (например, в SomeOtherApiClient), а там ему установят новый BaseAddress или Timeout, да еще в другом потоке...

Чем не устраивает предложенное выше решение (Client управляет временем жизни HttpClient). Оно свободно от всех вышеуказанных проблем.

2018-11-11 10:10 UTC, ili commented on Yandex.Checkout.V3/Client.cs
> +        private readonly HttpClient _httpClient = new HttpClient();
Тем что вызывающий код не сможет управлять временем жизни HttpClient. Даже не смотря на то, что есть ряд проблем с использованием HttpClient как стэндэлойна, это рекомендованая практика. Так же стэндэлоун крайне позитивно сказывается на производительности. 

Таким образом мы либо можем передать клиента и тогда уже вызывающий код отвечает за стратегию его использования и утилизации, либо оставить это на успотрение Client

2018-11-11 16:32 UTC, bzaar commented on Yandex.Checkout.V3/Client.cs
> +        private readonly HttpClient _httpClient = new HttpClient();
Поддерживаю "оставить это [время жизни HttpClient] на успотрение Client".  Таким образом пользователь Client может управлять временем жизни HttpClient, создавая и уничтожая Client. Принимается?

2018-11-12 00:40 UTC, bzaar commented
Конфликты "порешал" :)

2018-12-04 05:28 UTC, merged